
/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html, css, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";

export const FhiIconChevronRightSelector = "fhi-icon-chevron-right";

@customElement(FhiIconChevronRightSelector)
export class FhiIconChevronRight extends LitElement {
  @property({ type: String }) color: string = "currentcolor";
  @property({ type: String }) size: string | number = 'medium';

  private get sizeValue(): string {
    const sizeMap = {
      xsmall: '1rem',
      small: '1.25rem',
      medium: '1.5rem',
      large: '2rem'
    };
    const unitRegex = /^\d+(\.\d+)?(px|rem)?$/;
    if (typeof this.size === 'number' && this.size > 0) {
      return `${this.size}px`;
    }
    if (typeof this.size === 'string' && unitRegex.test(this.size)) {
      return this.size;
    }
    if (this.size in sizeMap) {
      return sizeMap[this.size as keyof typeof sizeMap];
    }
    return '2.5rem';
  }

  render() {
    return html`
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="${this.sizeValue}" height="${this.sizeValue}" fill="${this.color}"><path d="M8.47 5.47a.75.75 0 0 1 1.004-.052l.056.052 6 6 .052.056a.75.75 0 0 1 0 .948l-.052.056-6 6a.75.75 0 1 1-1.06-1.06L13.94 12 8.47 6.53l-.052-.056A.75.75 0 0 1 8.47 5.47"/></svg>
    `;
  }
      
  static styles = css`
    :host {
      display: flex;
      max-height: min-content;
      max-width: min-content;
    }
  `;
  }
