
/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html, css, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";

export const FhiIconInfoSelector = "fhi-icon-info";

@customElement(FhiIconInfoSelector)
export class FhiIconInfo extends LitElement {
  @property({ type: String }) color: string = "currentcolor";
  @property({ type: String }) size: 'xsmall' | 'small' | 'medium' | 'large' | number | string = 'medium';
  private get _size(): string {
    switch (this.size) {
      case 'xsmall': 
        return '16px'; 
      case 'small':
        return '20px';
      case 'medium':
        return '24px'; 
      case 'large':
        return '32px'; 
      default:
        if (String(this.size).endsWith('px') || String(this.size).endsWith('rem')) {
          return String(this.size);
        }
        if (isNaN(Number(this.size))) {
          console.warn(`Invalid size value: ${this.size}. Falling back to default size '24px'.`)
          return '24px';
        }
        return `${this.size}px`;
    }
  }

  render() {
    return html`
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="${this._size}" height="${this._size}" fill="${this.color}"><path fill-rule="evenodd" d="M12.112 5.005 12.01 5H12a1 1 0 1 0 0 2h.01l.102-.005a1 1 0 0 0 0-1.99M10 18.75h4a.75.75 0 0 0 0-1.5h-1.25V10a.75.75 0 0 0-.673-.746L12 9.25h-2a.75.75 0 0 0 0 1.5h1.25v6.5H10a.75.75 0 0 0 0 1.5" clip-rule="evenodd"/></svg>
    `;
  }
      
  static styles = css`
    :host {
      display: flex;
      max-height: min-content;
      max-width: min-content;
    }
  `;
  }
