
/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html, css, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";

export const FhiIconChevronsLeftSelector = "fhi-icon-chevrons-left";

@customElement(FhiIconChevronsLeftSelector)
export class FhiIconChevronsLeft extends LitElement {
  @property({ type: String }) color: string = "currentcolor";
  @property({ type: String }) size: string | number = 'medium';

  private get sizeValue(): string {
    const sizeMap = {
      xsmall: '1rem',
      small: '1.25rem',
      medium: '1.5rem',
      large: '2rem'
    };
    const unitRegex = /^\d+(\.\d+)?(px|rem)?$/;
    if (typeof this.size === 'number' && this.size > 0) {
      return `${this.size}px`;
    }
    if (typeof this.size === 'string' && unitRegex.test(this.size)) {
      return this.size;
    }
    if (this.size in sizeMap) {
      return sizeMap[this.size as keyof typeof sizeMap];
    } 
    return '1.5rem';
  }

  render() {
    return html`
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="${this.sizeValue}" height="${this.sizeValue}" fill="${this.color}"><path d="M10.526 6.418a.75.75 0 0 1 1.056 1.056l-.052.056L7.06 12l4.47 4.47.052.056a.75.75 0 0 1-1.056 1.056l-.056-.052-5-5a.75.75 0 0 1 0-1.06l5-5zm7 0a.75.75 0 0 1 1.056 1.056l-.052.056L14.06 12l4.47 4.47.052.056a.75.75 0 0 1-1.056 1.056l-.056-.052-5-5a.75.75 0 0 1 0-1.06l5-5z"/></svg>
    `;
  }
      
  static styles = css`
    :host {
      display: flex;
      max-height: min-content;
      max-width: min-content;
    }
  `;
  }
