/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html, css, LitElement } from 'lit';
import { customElement, property } from 'lit/decorators.js';

export const FhiIconShareSelector = 'fhi-icon-share';

@customElement(FhiIconShareSelector)
export class FhiIconShare extends LitElement {
  @property({ type: String }) color: string =
    'var(--fhi-color-neutral-text-default)';

  @property({ type: Number }) size: number = 24;

  render() {
    return html`
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        width="${this.size}"
        height="${this.size}"
        fill="${this.color}"
      >
        <path
          fill-rule="evenodd"
          d="M18 2.75a2.25 2.25 0 1 0 0 4.5 2.25 2.25 0 0 0 0-4.5m-2.796 4.749a3.75 3.75 0 1 0-.756-1.295L8.795 9.5a3.75 3.75 0 1 0 0 4.997l5.653 3.294a3.75 3.75 0 1 0 .758-1.294l-5.654-3.295a3.76 3.76 0 0 0 0-2.406zm-7.286 3.324a1 1 0 0 0 .052.089c.178.322.28.693.28 1.088a2.24 2.24 0 0 1-.332 1.177A2.249 2.249 0 0 1 3.75 12a2.25 2.25 0 0 1 4.168-1.177m8.086 7.138a.8.8 0 0 0 .112-.192 2.25 2.25 0 1 1-.113.192"
          clip-rule="evenodd"
        />
      </svg>
    `;
  }

  static styles = css`
    :host {
      display: flex;
      max-height: min-content;
      max-width: min-content;
    }
  `;
}
