
/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html, css, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";

export const FhiIconArrowRightSelector = "fhi-icon-arrow-right";

@customElement(FhiIconArrowRightSelector)
export class FhiIconArrowRight extends LitElement {
  @property({ type: String }) color: string = "currentcolor";
  @property({ type: String }) size: string = 'medium';
  private get sizeValue(): string {
    switch (this.size) {
      case 'xsmall': 
        return '16px'; 
      case 'small':
        return '20px';
      case 'medium':
        return '24px'; 
      case 'large':
        return '32px'; 
      default:
        if (!isNaN(Number(this.size))) {
          return `${this.size}px`;
        } else {
          return '24px';
        }
    }
  }

  render() {
    return html`
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="${this.sizeValue}" height="${this.sizeValue}" fill="${this.color}"><path d="M11.47 4.47a.75.75 0 0 1 1.004-.052l.056.052 7 7 .052.056a.75.75 0 0 1 0 .948l-.052.056-7 7a.75.75 0 1 1-1.06-1.06l5.72-5.72H5a.75.75 0 0 1 0-1.5h12.19l-5.72-5.72-.052-.056a.75.75 0 0 1 .052-1.004"/></svg>
    `;
  }
      
  static styles = css`
    :host {
      display: flex;
      max-height: min-content;
      max-width: min-content;
    }
  `;
  }
