/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html, css, LitElement } from 'lit';
import { customElement, property } from 'lit/decorators.js';

export const FhiIconExpandSelector = 'fhi-icon-expand';

@customElement(FhiIconExpandSelector)
export class FhiIconExpand extends LitElement {
  @property({ type: String }) color: string =
    'var(--fhi-color-neutral-text-default)';

  @property({ type: Number }) size: number = 24;

  render() {
    return html`
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        width="${this.size}"
        height="${this.size}"
        fill="${this.color}"
      >
        <path
          fill-rule="evenodd"
          d="M2.25 3A.75.75 0 0 1 3 2.25h4.8a.75.75 0 0 1 0 1.5H4.81l4.72 4.72a.75.75 0 0 1-1.06 1.06L3.75 4.81V7.8a.75.75 0 0 1-1.5 0zm13.2 0a.75.75 0 0 1 .75-.75H21a.75.75 0 0 1 .75.75v4.8a.75.75 0 0 1-1.5 0V4.81l-4.72 4.72a.75.75 0 1 1-1.06-1.06l4.72-4.72H16.2a.75.75 0 0 1-.75-.75M9.53 14.47a.75.75 0 0 1 0 1.06l-4.72 4.72H7.8a.75.75 0 0 1 0 1.5H3a.75.75 0 0 1-.75-.75v-4.8a.75.75 0 0 1 1.5 0v2.99l4.72-4.72a.75.75 0 0 1 1.06 0m4.94 0a.75.75 0 0 1 1.06 0l4.72 4.72V16.2a.75.75 0 0 1 1.5 0V21a.75.75 0 0 1-.75.75h-4.8a.75.75 0 0 1 0-1.5h2.99l-4.72-4.72a.75.75 0 0 1 0-1.06"
          clip-rule="evenodd"
        />
      </svg>
    `;
  }

  static styles = css`
    :host {
      display: flex;
      max-height: min-content;
      max-width: min-content;
    }
  `;
}
