
/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html, css, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";

export const FhiIconArrowLeftSelector = "fhi-icon-arrow-left";

@customElement(FhiIconArrowLeftSelector)
export class FhiIconArrowLeft extends LitElement {
  @property({ type: String }) color: string = "currentcolor";
  @property({ type: String }) size: 'xsmall' | 'small' | 'medium' | 'large' | number | `${number}px` | `${number}rem` = 'medium';
  private get _size(): string {
    switch (this.size) {
      case 'xsmall': 
        return '16px'; 
      case 'small':
        return '20px';
      case 'medium':
        return '24px'; 
      case 'large':
        return '32px'; 
      default:
        if (String(this.size).endsWith('px') || String(this.size).endsWith('rem')) {
          return String(this.size);
        }
        if (isNaN(Number(this.size))) {
          console.warn(`Invalid size value: ${this.size}. Falling back to default size '24px'.`)
          return '24px';
        }
        return `${this.size}px`;
    }
  }

  render() {
    return html`
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="${this._size}" height="${this._size}" fill="${this.color}"><path d="M11.47 4.47a.75.75 0 1 1 1.06 1.06l-5.72 5.72H19a.75.75 0 1 1 0 1.5H6.81l5.72 5.72.052.056a.75.75 0 0 1-1.056 1.056l-.056-.052-7-7a.75.75 0 0 1 0-1.06z"/></svg>
    `;
  }
      
  static styles = css`
    :host {
      display: flex;
      max-height: min-content;
      max-width: min-content;
    }
  `;
  }
