/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html, css, LitElement } from 'lit';
import { customElement, property } from 'lit/decorators.js';

export const FhiIconBellSelector = 'fhi-icon-bell';

@customElement(FhiIconBellSelector)
export class FhiIconBell extends LitElement {
  @property({ type: String }) color: string =
    'var(--fhi-color-neutral-text-default)';

  @property({ type: Number }) size: number = 24;

  render() {
    return html`
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        width="${this.size}"
        height="${this.size}"
        fill="${this.color}"
      >
        <path
          fill-rule="evenodd"
          d="M12 2.75A5.25 5.25 0 0 0 6.75 8c0 3.61-.775 5.986-1.592 7.484a9 9 0 0 1-.468.766h14.62a9 9 0 0 1-.468-.766C18.025 13.986 17.25 11.611 17.25 8A5.25 5.25 0 0 0 12 2.75m9.423 13.63-.009-.006-.063-.05a3 3 0 0 1-.275-.262 6.2 6.2 0 0 1-.918-1.296C19.475 13.514 18.75 11.39 18.75 8a6.75 6.75 0 0 0-13.5 0c0 3.39-.725 5.514-1.408 6.766a6.2 6.2 0 0 1-.918 1.296 3 3 0 0 1-.338.312l-.009.007A.75.75 0 0 0 3 17.75h18a.75.75 0 0 0 .423-1.37M9.939 20.344a.75.75 0 0 1 1.018.296 1.19 1.19 0 0 0 2.086 0 .75.75 0 1 1 1.314.722 2.69 2.69 0 0 1-4.714 0 .75.75 0 0 1 .296-1.018"
          clip-rule="evenodd"
        />
      </svg>
    `;
  }

  static styles = css`
    :host {
      display: flex;
      max-height: min-content;
      max-width: min-content;
    }
  `;
}
