/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html, css, LitElement } from 'lit';
import { customElement, property } from 'lit/decorators.js';

export const FhiIconRotateLeftSelector = 'fhi-icon-rotate-left';

@customElement(FhiIconRotateLeftSelector)
export class FhiIconRotateLeft extends LitElement {
  @property({ type: String }) color: string =
    'var(--fhi-color-neutral-text-default)';

  @property({ type: Number }) size: number = 24;

  render() {
    return html`
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        width="${this.size}"
        height="${this.size}"
        fill="${this.color}"
      >
        <path
          fill-rule="evenodd"
          d="M11.997 2.25H12A9.75 9.75 0 1 1 2.25 12a.75.75 0 0 1 1.5 0 8.25 8.25 0 1 0 8.251-8.25 9 9 0 0 0-6.215 2.525l-.975.975H8a.75.75 0 1 1 0 1.5H3A.75.75 0 0 1 2.25 8V3a.75.75 0 1 1 1.5 0v3.19l.98-.98.009-.01a10.5 10.5 0 0 1 7.258-2.95"
          clip-rule="evenodd"
        />
      </svg>
    `;
  }

  static styles = css`
    :host {
      display: flex;
      max-height: min-content;
      max-width: min-content;
    }
  `;
}
