/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html, css, LitElement } from 'lit';
import { customElement, property } from 'lit/decorators.js';

export const FhiIconUserSelector = 'fhi-icon-user';

@customElement(FhiIconUserSelector)
export class FhiIconUser extends LitElement {
  @property({ type: String }) color: string =
    'var(--fhi-color-neutral-text-default)';

  @property({ type: Number }) size: number = 24;

  render() {
    return html`
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        width="${this.size}"
        height="${this.size}"
        fill="${this.color}"
      >
        <path
          fill-rule="evenodd"
          d="M12 3.75a4.25 4.25 0 1 0 0 8.5 4.25 4.25 0 0 0 0-8.5m3.125 9.077a5.75 5.75 0 1 0-6.25 0A8.75 8.75 0 0 0 3.25 21a.75.75 0 0 0 1.5 0 7.25 7.25 0 1 1 14.5 0 .75.75 0 0 0 1.5 0 8.75 8.75 0 0 0-5.625-8.173"
          clip-rule="evenodd"
        />
      </svg>
    `;
  }

  static styles = css`
    :host {
      display: flex;
      max-height: min-content;
      max-width: min-content;
    }
  `;
}
