
/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html, css, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";

export const FhiIconSquareSelector = "fhi-icon-square";

@customElement(FhiIconSquareSelector)
export class FhiIconSquare extends LitElement {
  @property({ type: String }) color: string = "currentcolor";
  @property({ type: String }) size: string | number = 'medium';

  private get sizeValue(): string {
    const sizeMap = {
      xsmall: '1rem',
      small: '1.25rem',
      medium: '1.5rem',
      large: '2rem'
    };
    const unitRegex = /^\d+(\.\d+)?(px|rem)?$/;
    if (typeof this.size === 'number' && this.size > 0) {
      return `${this.size}px`;
    }
    if (typeof this.size === 'string' && unitRegex.test(this.size)) {
      return this.size;
    }
    if (this.size in sizeMap) {
      return sizeMap[this.size as keyof typeof sizeMap];
    }
    return '2.5rem';
  }

  render() {
    return html`
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="${this.sizeValue}" height="${this.sizeValue}" fill="${this.color}"><path d="M20.25 5c0-.69-.56-1.25-1.25-1.25H5c-.69 0-1.25.56-1.25 1.25v14c0 .69.56 1.25 1.25 1.25h14c.69 0 1.25-.56 1.25-1.25zm1.5 14A2.75 2.75 0 0 1 19 21.75H5A2.75 2.75 0 0 1 2.25 19V5A2.75 2.75 0 0 1 5 2.25h14A2.75 2.75 0 0 1 21.75 5z"/></svg>
    `;
  }
      
  static styles = css`
    :host {
      display: flex;
      max-height: min-content;
      max-width: min-content;
    }
  `;
  }
