/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html, css, LitElement } from 'lit';
import { customElement, property } from 'lit/decorators.js';

export const FhiIconPrinterSelector = 'fhi-icon-printer';

@customElement(FhiIconPrinterSelector)
export class FhiIconPrinter extends LitElement {
  @property({ type: String }) color: string =
    'var(--fhi-color-neutral-text-default)';

  @property({ type: Number }) size: number = 24;

  render() {
    return html`
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        width="${this.size}"
        height="${this.size}"
        fill="${this.color}"
      >
        <path
          fill-rule="evenodd"
          d="M7 2.75a.25.25 0 0 0-.25.25v5.25h10.5V3a.25.25 0 0 0-.25-.25zm11.75 5.5V3A1.75 1.75 0 0 0 17 1.25H7A1.75 1.75 0 0 0 5.25 3v5.25H4A2.75 2.75 0 0 0 1.25 11v5A2.75 2.75 0 0 0 4 18.75h1.25V21c0 .966.784 1.75 1.75 1.75h10A1.75 1.75 0 0 0 18.75 21v-2.25H20A2.75 2.75 0 0 0 22.75 16v-5A2.75 2.75 0 0 0 20 8.25zM18 9.75H4A1.25 1.25 0 0 0 2.75 11v5A1.25 1.25 0 0 0 4 17.25h1.25V15c0-.966.784-1.75 1.75-1.75h10c.966 0 1.75.784 1.75 1.75v2.25H20A1.25 1.25 0 0 0 21.25 16v-5A1.25 1.25 0 0 0 20 9.75zM17.25 18v-3a.25.25 0 0 0-.25-.25H7a.25.25 0 0 0-.25.25v6c0 .138.112.25.25.25h10a.25.25 0 0 0 .25-.25z"
          clip-rule="evenodd"
        />
      </svg>
    `;
  }

  static styles = css`
    :host {
      display: flex;
      max-height: min-content;
      max-width: min-content;
    }
  `;
}
