/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html, css, LitElement } from 'lit';
import { customElement, property } from 'lit/decorators.js';

export const FhiIconRefreshSelector = 'fhi-icon-refresh';

@customElement(FhiIconRefreshSelector)
export class FhiIconRefresh extends LitElement {
  @property({ type: String }) color: string =
    'var(--fhi-color-neutral-text-default)';

  @property({ type: Number }) size: number = 24;

  render() {
    return html`
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        width="${this.size}"
        height="${this.size}"
        fill="${this.color}"
      >
        <path
          fill-rule="evenodd"
          d="M11.999 3.75A8.25 8.25 0 0 0 3.75 12a.75.75 0 0 1-1.5 0A9.75 9.75 0 0 1 12 2.25h.003A10.5 10.5 0 0 1 19.26 5.2l.01.01.979.98V3a.75.75 0 0 1 1.5 0v5a.75.75 0 0 1-.75.75h-5a.75.75 0 0 1 0-1.5h3.19l-.976-.975A9 9 0 0 0 12 3.75m5.835 14.084A8.25 8.25 0 0 0 20.25 12a.75.75 0 0 1 1.5 0A9.75 9.75 0 0 1 12 21.75h-.003A10.5 10.5 0 0 1 4.74 18.8l-.01-.01-.979-.98V21a.75.75 0 0 1-1.5 0v-5a.75.75 0 0 1 .75-.75h5a.75.75 0 0 1 0 1.5H4.81l.976.975A9 9 0 0 0 12 20.25a8.25 8.25 0 0 0 5.833-2.416"
          clip-rule="evenodd"
        />
      </svg>
    `;
  }

  static styles = css`
    :host {
      display: flex;
      max-height: min-content;
      max-width: min-content;
    }
  `;
}
