/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html, css, LitElement } from 'lit';
import { customElement, property } from 'lit/decorators.js';

export const FhiIconCircleQuestionSelector = 'fhi-icon-circle-question';

@customElement(FhiIconCircleQuestionSelector)
export class FhiIconCircleQuestion extends LitElement {
  @property({ type: String }) color: string =
    'var(--fhi-color-neutral-text-default)';

  @property({ type: Number }) size: number = 24;

  render() {
    return html`
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        width="${this.size}"
        height="${this.size}"
        fill="${this.color}"
      >
        <path
          fill-rule="evenodd"
          d="M12 2.75a9.25 9.25 0 1 0 0 18.5 9.25 9.25 0 0 0 0-18.5M1.25 12C1.25 6.063 6.063 1.25 12 1.25S22.75 6.063 22.75 12 17.937 22.75 12 22.75 1.25 17.937 1.25 12M12.3 7.778a2.25 2.25 0 0 0-2.503 1.47.75.75 0 0 1-1.415-.497 3.75 3.75 0 0 1 7.288 1.25c0 1.397-1.039 2.343-1.834 2.873a7.8 7.8 0 0 1-1.631.82l-.032.012-.01.004h-.004v.001h-.001L11.92 13l.237.711a.75.75 0 0 1-.475-1.422l.003-.001.017-.006.08-.03a6.3 6.3 0 0 0 1.222-.626c.705-.47 1.166-1.024 1.166-1.626v-.001a2.25 2.25 0 0 0-1.87-2.221M15.67 10h-.75zM12 16a1 1 0 1 0 0 2h.01a1 1 0 1 0 0-2z"
          clip-rule="evenodd"
        />
      </svg>
    `;
  }

  static styles = css`
    :host {
      display: flex;
      max-height: min-content;
      max-width: min-content;
    }
  `;
}
