
/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html } from 'lit';
import type { Meta, StoryObj } from '@storybook/web-components';
import { ifDefined } from 'lit/directives/if-defined.js';

import { FhiIconArrowDownLeft } from './fhi-icon-arrow-down-left.component';

new FhiIconArrowDownLeft();

const meta: Meta<FhiIconArrowDownLeft> = {
  title: 'Ikoner',
  component: 'fhi-icon-arrow-down-left',
  parameters: {},
  decorators: [],
  render: args =>
    html`<fhi-icon-arrow-down-left
      color=${ifDefined(args.color)}
      size=${ifDefined(args.size)}
    ></fhi-icon-arrow-down-left>`,
  argTypes: {
    color: {
      control: 'text',
      description:
        'Setter farge på ikonet. Skal helst være et farge token. Se [Farge Tokens](https://designsystem.fhi.no/?path=/docs/design-tokens-farger--docs)',
      defaultValue: { summary: 'currentcolor' },
    },
    size: {
      control: 'select',
      options: ['xsmall', 'small', 'medium', 'large', '16', '20', '24', '32'],
      description: 'Setter størrelsen på ikonet. Kan være en av de forhåndsdefinerte størrelsene (<code>xsmall</code>, <code>small</code>, <code>medium</code> eller <code>large</code>) eller en egendefinert størrelse. Tallverdier blir angitt som px.',
      defaultValue: { summary: 'medium' },
    },
  },
};

type Story = StoryObj<FhiIconArrowDownLeft>;

export const Preview: Story = {
  tags: ['!dev'],
  args: {
    color: 'var(--fhi-color-neutral-text-default)',
    size: 'medium',
  },
};

export default meta;

