
/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html, css, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";

export const FhiIconSearchSelector = "fhi-icon-search";

@customElement(FhiIconSearchSelector)
export class FhiIconSearch extends LitElement {
  @property({ type: String }) color: string = "currentcolor";
  @property({ type: String }) size: 'xsmall' | 'small' | 'medium' | 'large' | number = 'medium';
  private get _size(): string {
    switch (this.size) {
      case 'xsmall': 
        return '16px'; 
      case 'small':
        return '20px';
      case 'medium':
        return '24px'; 
      case 'large':
        return '32px'; 
      default:
        if (/^-?\d*\.?\d+(px|rem)$/.test(String(this.size))) {
          return String(this.size);
        }
        if (isNaN(Number(this.size))) {
          console.warn(`Invalid size value: ${this.size}. Falling back to default size '24px'.`)
          return '24px';
        }
        return `${this.size}px`;
    }
  }

  render() {
    return html`
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="${this._size}" height="${this._size}" fill="${this.color}"><path d="M18.25 11a7.25 7.25 0 1 0-14.5 0 7.25 7.25 0 0 0 14.5 0m1.5 0c0 2.146-.774 4.11-2.057 5.633l3.837 3.837.052.056a.75.75 0 0 1-1.056 1.056l-.056-.052-3.837-3.837A8.75 8.75 0 1 1 19.75 11"/></svg>
    `;
  }
      
  static styles = css`
    :host {
      display: flex;
      max-height: min-content;
      max-width: min-content;
    }
  `;
  }
