name: Guard - BREAKING CHANGE

permissions:
  contents: write
  id-token: write

on:
  workflow_dispatch:
  push:
    branches:
      - 82-split-up-the-release-pipeline

jobs:
  run:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Guard - BREAKING CHANGE should not be in body
        id: guard_breaking_change
        run: |
          LAST_COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          echo "Commit message: \"$LAST_COMMIT_MESSAGE\""
          if [[ "$LAST_COMMIT_MESSAGE" == *"BREAKING CHANGE"* ]]; then
              echo "ERROR: Commit message should not include 'BREAKING CHANGE'."
              exit 1
          fi
        shell: bash
